# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

$qsConfig = ii
exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Environment variables
source=hyprland/env.conf
source=custom/env.conf

# Defaults
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=hyprland/colors.conf
source=custom/colors-override.conf
source=hyprland/keybinds.conf

# Custom 
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf





# WhatsApp Web sidebar
windowrule = match:class ^(whatsapp-web)$, float on
windowrule = match:class ^(whatsapp-web)$, size 500 800
windowrule = match:class ^(whatsapp-web)$, move 20 100

# WhatsApp Native Desktop - Pin to sidebar
windowrule = match:class ^(whatsapp-for-linux|whatsapp-linux-desktop)$, float on
windowrule = match:class ^(whatsapp-for-linux|whatsapp-linux-desktop)$, pin on
windowrule = match:class ^(whatsapp-for-linux|whatsapp-linux-desktop)$, size 100% 100%
windowrule = match:class ^(whatsapp-for-linux|whatsapp-linux-desktop)$, move 0 0
