# This file is to be overwritten by nwg-displays if you choose to use it.
# nwg-displays is a graphical tool for managing monitors. 
# - Installation for Arch Linux: sudo pacman -S nwg-displays
# - Repo: https://github.com/nwg-piotr/nwg-displays

monitor = eDP-1, 2560x1600@165, 0x0, 1.25
monitor = HDMI-A-1, 1440x900@59.89, 0x0, 1, mirror, eDP-1


